Revert "DEV: Parse and install bundler version from Gemfile.lock (#98)"
This reverts commit 25fc00a76332128d2fea72849f0d7baa3f50a048.

This causes a RuntimeError during upgrade, because the `discourse` user does not have permission to install system gems

```
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /usr/local/lib/ruby/gems/2.7.0 directory.
Docker Manager: FAILED TO UPGRADE
```